### ISSUE TITLE
Synced Charts are getting too many Options overwritten.

### ISSUE THREAD

**Issue by cdeutsch** [apexcharts/react-apexcharts#182] opened 2020-05-27 16:57 UTC
I have multiple `<ApexChart>`'s that share a `group` in order to synchronize the tooltips.

![image](https://user-images.githubusercontent.com/404765/83048404-25f52d80-a00f-11ea-8023-ac5a323a8ce1.png)

When I hover over "MAX(value)", they'll all get the same `title`

![image](https://user-images.githubusercontent.com/404765/83048503-49b87380-a00f-11ea-8e9a-cf894b50b594.png)

I tracked it down to multiple issues.

#### 1. Something in [apexcharts.js](https://github.com/apexcharts/apexcharts.js) is modifying `ApexCharts.props.options` directly.

On the 2nd render of `ApexCharts`, `this.chart.updateOptions(this.getConfig())` is being called because the `prevOptions !== currentOptions`
https://github.com/apexcharts/react-apexcharts/blob/7345fdca622358f181aa64e1cdfc76f592f4bdf0/src/react-apexcharts.jsx#L116

When I pause the debugger, something has added `xaxis.convertedCatToNumeric: false` to my `props.options`

To get around this you should probably:
A. Do a deep clone of `options` in `getConfig()`.
B. Deep clone `options` in `apexcharts.js`.
C. Stop modifying `options` in `apexcharts.js`

#### 2. `_updateOptions` in [apexcharts.js](https://github.com/apexcharts/apexcharts.js) shouldn't update so many `options` for Synced Charts
https://github.com/apexcharts/apexcharts.js/blob/433fccce57a1dfd3ff1b67a731818189146ca7ca/src/modules/helpers/UpdateHelpers.js#L63

What's happening in my example, is you're taking the `options` for the bottom chart and applying it to all the charts (minus the `series`).

I'm not sure the reasoning for doing this, but options like `title.text` definitely should not be synced, and I imagine many others.

**Comment by cstrat** [comment] 2021-04-19 00:27
I am having this issue too.

On the initial render everything looks great, but React re-renders when I scroll and then all my options are sync'd across the multiple graphs which means colours, axis labels and everything become the same.

**Comment by cstrat** [comment] 2021-04-19 03:29
Ok I worked out how to fix this for my example, unsure if it is the same thing that is happening to you.

I wasn't storing the graph options in React State. I had a generator function outputting the options.
Unsure why the behaviour didn't allow for this to work after the initial render...
Anyway, moving this logic into a `useEffect` where I set an object to have the state output from the generator it stopped the issue completely.

**Comment by karimkozman** [comment] 2022-02-07 14:46
> Ok I worked out how to fix this for my example, unsure if it is the same thing that is happening to you.
> 
> I wasn't storing the graph options in React State. I had a generator function outputting the options. Unsure why the behaviour didn't allow for this to work after the initial render... Anyway, moving this logic into a `useEffect` where I set an object to have the state output from the generator it stopped the issue completely.

@cstrat I tried your approach to pass the option state set in useEffect but still same issue after react re-renders. Am I missing something maybe? could you create a small codebox example if possible?

**Comment by joshribakoff-sm** [comment] 2022-04-26 19:45
I think that @cstrat likely made it so that Apex is mutating React state now, so the mutation persists between renders.

I can also confirm that under the hood Apex core mutates the `options.xAxis.type` to `numeric`. In react devtools, it "looks" like we are passing this prop even though we never did!

![Screen Shot 2022-04-26 at 12 10 35 PM](https://user-images.githubusercontent.com/97546767/165379584-eb3919eb-b257-404e-8614-9eaa0d8610d0.png)

It turns out Apex actually mutates the `options`, which triggers your wrapper to update and runs `componentDidUpdate` with the "numeric" axis, which blocks the page as all of our linked charts re-render, and makes them look corrupt since they are not intended to visualize on "numeric" scale.

On our end we pass a `key` prop to the charts which changes together with the dataset. We also copy pasted your source code into our repo and commented out the entire `componentDidUpdate`, basically forcing fresh unmount and mounts every time. We had to pass the `key` to force remounts on our end, and also disable `componentDidUpdate` in this library's code in order to prevent the updates triggered when Apex erroneously mutates the props.

**Comment by joshribakoff** [comment] 2022-04-27 01:18
Also confirming that simply deem cloning in getOptions() solves the problem as @cdeutsch suggests. This should be an easy PR

**Comment by Andynopol** [comment] 2022-12-15 19:02
Easy PR and 3 years late, the problem is still here. At this point, I think I am diching apexchart...

**Comment by kamzak** [comment] 2023-01-04 12:56
The easiest solution I have managed to work is just simply extract all options into separate variable: 
`var options = {
	colors: ['#fff'],
	chart: {
		id: 'earnings',
		group: 'results',
		type: 'area',
		foreColor: '#fff',
		zoom: {
			enabled: false,
		},
	},
	dataLabels: {
		enabled: false,
	},
	stroke: {
		curve: 'smooth',
		width: 3,
	},
	tooltip: {
		enabled: true,
		shared: false,
		theme: 'dark',
		x: {
			show: false,
			format: 'ddd'
		},
		y: {
			formatter: (value) => `${value} $`,
		},
	},
	grid: {
		show: false,
		xaxis: {
			lines: {
				show: false,
			},
		},
		yaxis: {
			lines: {
				show: false,
			},
		},
	},
	xaxis: {
		type: 'datetime',
		axisBorder: {
			show: false,
		},
		axisTicks: {
			show: false,
		},
		labels: {
			show: false,
		},
	},
	yaxis: {
		show: false,
		opposite: true,
	},
};`

And then make new state to hold it: 
`const [chartOptions, setChartOptions] = useState(options);`

Later on just pass it to your render Component:

`<ApexCharts
	options={chartOptions}
	series={series}
	type='line'
	height={100}
	key={0}
/>`

In my case it worked perfectly and I had to make this only on the one of my synced charts.

**Comment by joshribakoff** [comment] 2023-01-04 15:54
@kamzak thanks for sharing, however lots of us actually do need the chart options to be dynamically updated.

**Comment by Inna-7** [comment] 2024-03-05 12:40
> The easiest solution I have managed to work is just simply extract all options into separate variable: `` var options = { colors: ['#fff'], chart: { id: 'earnings', group: 'results', type: 'area', foreColor: '#fff', zoom: { enabled: false, }, }, dataLabels: { enabled: false, }, stroke: { curve: 'smooth', width: 3, }, tooltip: { enabled: true, shared: false, theme: 'dark', x: { show: false, format: 'ddd' }, y: { formatter: (value) => ``${value} $``, }, }, grid: { show: false, xaxis: { lines: { show: false, }, }, yaxis: { lines: { show: false, }, }, }, xaxis: { type: 'datetime', axisBorder: { show: false, }, axisTicks: { show: false, }, labels: { show: false, }, }, yaxis: { show: false, opposite: true, }, }; ``
> 
> And then make new state to hold it: `const [chartOptions, setChartOptions] = useState(options);`
> 
> Later on just pass it to your render Component:
> 
> `<ApexCharts options={chartOptions} series={series} type='line' height={100} key={0} />`
> 
> In my case it worked perfectly and I had to make this only on the one of my synced charts.

This one worked, but they neeed to fix this

**Comment by RafaelCENG** [comment] 2024-06-27 08:16
bump!

**Comment by joshribakoff** [comment] 2024-06-27 14:54
> they neeed to fix this

technically they don’t. consider fixing it yourself.

**Closed** 2024-09-14 14:29 UTC
Labels: no-issue-activity
