### ISSUE TITLE
Radial chart tooltip flickers on data point hover

### ISSUE THREAD

**Issue by ZahidChandio** [apexcharts/react-apexcharts#657] opened 2024-12-01 09:16 UTC
When hovering over data points in the ApexCharts radial chart, the tooltip flickers and behaves inconsistently, making it difficult to read. This issue affects user experience and appears regardless of tooltip customization settings.

_Results snippet_

https://github.com/user-attachments/assets/d7bcc692-fc4f-470b-b472-454cf00b272b

[Reproduce link](https://codesandbox.io/p/sandbox/fpy4nt)

It looks worse on the CodeSandbox.

**Comment by junedchhipa** [comment] 2024-12-05 10:32
The flickering occurs because you are re-rendering chart on every datapoint mouse events.
You might need to re-think the implementation for changing chart colors on mouse events.

Closing as this is not a bug.

**Closed by junedchhipa** 2024-12-05 10:32 UTC

**Comment by ZahidChandio** [comment] 2024-12-05 11:45
@junedchhipa, can you suggest something to achieve to this?
