### ISSUE TITLE
Create React App - tests fails

### ISSUE THREAD

**Issue by JCQuintas** [apexcharts/react-apexcharts#4] opened 2018-08-23 20:26 UTC
Issue happens because react-apexcharts is not pre-compiled.

Steps to reproduce:

`npx create-react-app crash-test`

`cd crash-test`

`npm install react-apexcharts`

_App.js_
```import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import Chart from 'react-apexcharts'

const p = {
  options: {
    fill: {
      type: 'gradient',
      gradient: {
        shade: 'dark',
        shadeIntensity: 1,
        type: 'horizontal',
        opacityFrom: 1,
        opacityTo: 1,
        stops: [0, 100, 100, 100],
      },
    },
    stroke: {
      width: 7,
      curve: 'smooth',
    },
    xaxis: {
      type: 'datetime',
      categories: [
        '1/11/2000',
        '2/11/2000',
        '3/11/2000',
        '4/11/2000',
        '5/11/2000',
      ],
    },
  },
  series: [
    {
      name: 'Likes',
      data: [4, 3, 10, 9, 29],
    },
  ],
}

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <Chart {...p}/>
      </div>
    );
  }
}

export default App;
```

`npm run test`

`npm run build`

Testing doesn't give any usefull error, but trying to build outputs:
```
Failed to minify the code from this file:

 	./node_modules/react-apexcharts/dist/react-apexcharts.js:5

Read more here: http://bit.ly/2tRViJ9
```

**Comment by omarpando** [comment] 2018-08-23 21:33
I am getting the same error:
```
Failed to minify the code from this file:

        ./node_modules/react-apexcharts/dist/react-apexcharts.js:5

Read more here: http://bit.ly/2tRViJ9
```

**Comment by junedchhipa** [comment] 2018-08-24 05:47
Confirmed the bug and fixed it in https://github.com/apexcharts/react-apexcharts/commit/c69d3346644026f5985953b1aea8e4578e8540d4

Changed the "main" file to pre-compiled react-apexcharts.min.js in package.json. 
Try the new version react-apexcharts@1.0.4

Thanks for reporting

**Comment by JCQuintas** [comment] 2018-08-24 16:46
I couldn't find a way to fix it. I'll try to disable specific tests in order for them to pass.

But among the things I tried were: 

- Ejecting
- setting jest automock to true
- setting jest to ignore apexcharts and svg.js modules
- importing svg.js into the setup both as a global and as a scoped variable

**Comment by junedchhipa** [comment] 2018-08-24 16:51
@JCQuintas I just tried #2 and #3 of what you did with no luck :(

**Comment by JCQuintas** [comment] 2018-08-24 21:06
What I ended up doing was to remove any `.test` related to a component that uses react-apexcharts from my code. Then, on my component I require `const Chart = require('react-apexcharts').default` inside the function or class that uses it. For now the tests are passing. 💥

**Comment by junedchhipa** [comment] 2018-08-24 21:13
Good that you got it working by this. But, I definitely need to solve this issue as I can’t write tests for the core library too.

Tomorrow, I will try forking svg.js and try bundling the modules with webpack instead of gulp as they are currently doing it.

Maybe exporting svg as global variable from webpack will expose it to it’s dependencies.

**Comment by JCQuintas** [comment] 2018-08-24 21:16
Yeah, just posting here as a workaround for now if someone is looking for it. Good luck on that and give me a hit when you succeed :)

**Comment by junedchhipa** [comment] 2018-08-26 11:56
@JCQuintas - I spent a couple of hours trying to bundle svg.js modules with webpack instead of gulp - but got same results.
Luckily, I found a workaround directly in svg.js core file and the jest tests started to pass 😄 

I have pushed the latest patch apexcharts@1.3.12 and also upgraded the version of apexcharts in react-apexcharts.

Let me know, if everything works fine now

**Comment by JCQuintas** [comment] 2018-08-27 13:16
Working Great! 👍

**Comment by JCQuintas** [comment] 2018-08-27 14:35
Though now I'm getting a different error only when CI=true on my project, on a clean CRA app any test is breaking with the error:

```TypeError: Right-hand side of 'instanceof' is not an object
    at /Users/josequintas/Sources/top/node_modules/apexcharts/dist/apexcharts.min.js:1:314938
    at Object.filter (/Users/josequintas/Sources/top/node_modules/apexcharts/dist/apexcharts.min.js:1:314742)
    at Object.filterSVGElements (/Users/josequintas/Sources/top/node_modules/apexcharts/dist/apexcharts.min.js:1:314908)
    at create.lines (/Users/josequintas/Sources/top/node_modules/apexcharts/dist/apexcharts.min.js:1:366696)
    at create.rebuild (/Users/josequintas/Sources/top/node_modules/apexcharts/dist/apexcharts.min.js:1:366934)
    at create.attr (/Users/josequintas/Sources/top/node_modules/apexcharts/dist/apexcharts.min.js:1:344066)
    at create.attr (/Users/josequintas/Sources/top/node_modules/apexcharts/dist/apexcharts.min.js:1:343320)
    at t.value (/Users/josequintas/Sources/top/node_modules/apexcharts/dist/apexcharts.min.js:1:7377)
    at /Users/josequintas/Sources/top/node_modules/apexcharts/dist/apexcharts.min.js:1:46939
    at Array.map (<anonymous>)
    at t.value (/Users/josequintas/Sources/top/node_modules/apexcharts/dist/apexcharts.min.js:1:46648)
    at t.value (/Users/josequintas/Sources/top/node_modules/apexcharts/dist/apexcharts.min.js:1:39118)
    at t.value (/Users/josequintas/Sources/top/node_modules/apexcharts/dist/apexcharts.min.js:1:38889)
    at t.value (/Users/josequintas/Sources/top/node_modules/apexcharts/dist/apexcharts.min.js:1:142769)
    at t.create (/Users/josequintas/Sources/top/node_modules/apexcharts/dist/apexcharts.min.js:1:14500)
    at /Users/josequintas/Sources/top/node_modules/apexcharts/dist/apexcharts.min.js:1:141257
    at new Promise (<anonymous>)
    at t.value (/Users/josequintas/Sources/top/node_modules/apexcharts/dist/apexcharts.min.js:1:140961)
    at r.value (/Users/josequintas/Sources/top/node_modules/react-apexcharts/dist/react-apexcharts.min.js:1:2507)
    at commitLifeCycles (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:14362:22)
    at commitAllLifeCycles (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:15463:7)
    at HTMLUnknownElement.callCallback (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:100:14)
    at invokeEventListeners (/Users/josequintas/Sources/top/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
    at HTMLUnknownElementImpl._dispatch (/Users/josequintas/Sources/top/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
    at HTMLUnknownElementImpl.dispatchEvent (/Users/josequintas/Sources/top/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
    at HTMLUnknownElementImpl.dispatchEvent (/Users/josequintas/Sources/top/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:36:27)
    at HTMLUnknownElement.dispatchEvent (/Users/josequintas/Sources/top/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
    at Object.invokeGuardedCallbackDev (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:138:16)
    at invokeGuardedCallback (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:187:29)
    at commitRoot (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:15604:7)
    at completeRoot (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:16619:34)
    at performWorkOnRoot (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:16564:9)
    at performWork (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:16483:7)
    at performSyncWork (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:16455:3)
    at requestWork (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:16355:5)
    at scheduleWork$1 (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:16219:11)
    at scheduleRootUpdate (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:16786:3)
    at updateContainerAtExpirationTime (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:16813:10)
    at updateContainer (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:16840:10)
    at ReactRoot.Object.<anonymous>.ReactRoot.render (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:17123:3)
    at /Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:17263:14
    at unbatchedUpdates (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:16680:10)
    at legacyRenderSubtreeIntoContainer (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:17259:5)
    at Object.render (/Users/josequintas/Sources/top/node_modules/react-dom/cjs/react-dom.development.js:17318:12)
    at Object.<anonymous>.it (/Users/josequintas/Sources/top/src/App.test.js:7:22)
    at Object.asyncFn (/Users/josequintas/Sources/top/node_modules/jest-jasmine2/build/jasmine-async.js:68:30)
    at resolve (/Users/josequintas/Sources/top/node_modules/jest-jasmine2/build/queueRunner.js:38:12)
    at new Promise (<anonymous>)
    at mapper (/Users/josequintas/Sources/top/node_modules/jest-jasmine2/build/queueRunner.js:31:21)
    at Promise.resolve.then.el (/Users/josequintas/Sources/top/node_modules/p-map/index.js:46:16)
    at <anonymous>```

**Comment by junedchhipa** [comment] 2018-08-27 14:40
Can you tell me the steps to reproduce?
If I install a new CRA, will I be able to reproduce?

**Comment by JCQuintas** [comment] 2018-08-27 15:01
Yeah, same steps as above

**Comment by omarpando** [comment] 2018-08-27 15:12
It is working for me now. Using version ``` 1.0.5 ```. Thank you very much @junedchhipa.

**Comment by junedchhipa** [comment] 2018-08-28 10:38
@JCQuintas
I cannot reproduce the error on my side.
Created a fresh CRA, installed react-apexcharts and ran jest tests.
All tests passed.

If it is possible for you to do a codesandbox demo of your issue, I can have a closer look

**Comment by JCQuintas** [comment] 2018-08-28 14:26
@junedchhipa Tried setting up a codesandbox but there seems to be a bug with this.chart.destroy() that I can't reproduce locally.

`Cannot read property 'destroy' of null`

https://codesandbox.io/s/ry6jw3wmqq

**Comment by junedchhipa** [comment] 2018-08-28 14:44
Hi @JCQuintas 
Are you using yarn and npm together? I have read that using both will cause issues.
In your codesandbox, I just deleted the yarn file and it started working

https://codesandbox.io/s/ry4801mo24

Try removing node_modules, installing everything with `npm install` and then test again.

**Comment by junedchhipa** [comment] 2018-08-28 14:59
Ok, still the tests are failing.
I will look into it.

**Comment by JCQuintas** [comment] 2018-08-28 15:06
You are right, forgot to uninstall yarn on this machine. 

But my tests are still failing with `Right-hand side of 'instanceof' is not an object`. Which node and npm versions are you using? I tested on 

- node `v8.11.1` npm `v5.6.0`
- node `v10.9.0` npm `v6.2.0`

**Comment by junedchhipa** [comment] 2018-08-28 15:10
- npm v6.2.0 and node v8.9.4

**Comment by junedchhipa** [comment] 2018-08-28 16:50
Reproduced the error on my side with non-minified apexcharts.
Question - Are you using default `yarn test` or `npm test` to run the tests? Or are you using `jest` command.

Because, when I was using `yarn test` - I was getting the same errors as yours. So, here are the steps I got the tests to pass.

1.  I moved the test files to `__tests__` directory. 
2. I created a .babelrc file in the root with the following contents
```javascript
{
  "presets": ["env", "react"]
}
```
3. Changed the package.json `test` property to `jest` instead of `react-scripts test --env=jsdom`

It still gives me a warning `TypeError: Right-hand side of 'instanceof' is not an object` but the test passes for now.

I will look into the error later, let me know if this workaround fixes the issue

**Comment by JCQuintas** [comment] 2018-08-28 17:54
I use `npm test` to run `react-scripts test --env=jsdom`. I also figured the test script was the one breaking the tests. To run `jest` instead I would have to change a lot of configs in my main application, so I just disabled tests for components that use charts atm.

I also created a fork of this repo and added jest with simple mount/unmount tests to it. Will be creating a pull request soon so you can check if it's a good addition.

Tests are passing, but are displaying the following messages:

```
(node:52376) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'instance' of undefined
(node:52376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:52376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by junedchhipa** [comment] 2018-08-28 17:57
Yes, I saw the same message.
And these are the same errors which are preventing your tests to pass.

**Comment by junedchhipa** [comment] 2018-10-04 12:16
Closing this as I don't see a fix for it. Jest/jsdom doesn't play well with svg.js. I will keep track of jsdom releases and see if there is better support available in the future.

**Closed by junedchhipa** 2018-10-04 12:16 UTC
