### ISSUE TITLE
Radar chart yaxis fontSize issues

### ISSUE THREAD

**Issue by MiholapMaksim** [apexcharts/react-apexcharts#102] opened 2019-10-29 08:50 UTC
Hi! I try to use the Radar chart from the rechart library but unfortunately, I can't change font-size on the label - yaxis. If I change it on react dev tools it works fine. But in code, it only could changes the color of labels. Is someone had the same issues?

**Comment by junedchhipa** [comment] 2019-11-02 13:28
Closing as duplicate of https://github.com/apexcharts/apexcharts.js/issues/1034

**Closed by junedchhipa** 2019-11-02 13:28 UTC
