### ISSUE TITLE
yaxis logarithmic chart shifts down

### ISSUE THREAD

**Issue by mkantz84** [apexcharts/react-apexcharts#242] opened 2020-12-02 06:23 UTC
I'm using logarithmic chart, and in some cases the chart is "shifting" a little bit down and messes the UI.
It seems like when the numbers in the yAxis are big, the issue does not occure.
Also, when `yaxis.logarithmic` is `false` the issue does not occure.

![image](https://user-images.githubusercontent.com/22270407/100837174-611e6080-3479-11eb-9894-80e18e14fbf1.png)

Here is [codesandbox](https://codesandbox.io/s/unruffled-babbage-5glg6?file=/src/components/GoodChart.jsx)

I also posted an [issue ](https://github.com/apexcharts/apexcharts.js/issues/2084) in `apexcharts` repo

`apexcharts` version: 3.22.2
`react-apexcharts` version: 1.3.7

**Comment by junedchhipa** [comment] 2020-12-03 16:19
Duplicate of https://github.com/apexcharts/apexcharts.js/issues/2084

**Closed by junedchhipa** 2020-12-03 16:19 UTC
