### ISSUE TITLE
Updating options doesn't update chart when all series hidden

### ISSUE THREAD

**Issue by pnemi** [apexcharts/react-apexcharts#17] opened 2018-10-04 07:43 UTC
I cannot replicate this issue easily into minimal example but following thing happens:

1. I disable all series by unchecking them in legend
2. I change axis.min timestamp date (by changing some filter on our site, eg. from displaying data from 30 days ago to only 7 days ago)
3. I enable all series again but they just appear for a split of a second and then they stay invisible (tooltip somehow works)

**Comment by pnemi** [comment] 2018-10-04 08:02
Another observation to what I think is same problem.

1. I load my graph with data from 30 days ago
2. Change min date to 7 days ago
3. Clicking on zoom reset button in toolbar sets charts min date to 30 days ago again (inital config)

**Comment by junedchhipa** [comment] 2018-10-04 12:11
Hi @pnemi 
I reproduced al the issues you listed except the below one

> I enable all series again but they just appear for a split of a second and then they stay invisible (tooltip somehow works)
![issue-react-apexcharts](https://user-images.githubusercontent.com/17950663/46473060-9cbb3280-c7fc-11e8-8ea8-99d328ac987e.gif)

Can you please create a codepen? Or post your full config?

**Comment by pnemi** [comment] 2018-10-05 05:44
What do you mean exactly? That they stay visible? Could you please provide me the example you made so I can compare?

**Comment by junedchhipa** [comment] 2018-10-05 06:47
Here is a codepen example
https://codepen.io/apexcharts/pen/bmeYee

**Comment by pnemi** [comment] 2018-10-08 08:11
I really can't seem to reproduce my bug easily outside of our project.
(By the way I noticed using CodeSandbox that react-apexchart's apexcharts dependency version is outdated, it's using 1.4.something instead of +2.0...)

Here's a video capture at least, do you please have any clue what might be a problem?
https://streamable.com/nxab3

**Comment by junedchhipa** [comment] 2018-10-08 08:29
Thanks for the video. It will be helpful to dig more.
I will get back with an update soon

**Comment by junedchhipa** [comment] 2018-10-08 08:29
btw, are you using custom legend in your example?

**Comment by pnemi** [comment] 2018-10-08 08:46
Yes, since I was really confused that series can be toggled and our custom had checkmarks in their design, I added checkmarks icons.

**Comment by junedchhipa** [comment] 2018-10-10 06:50
Maybe, the custom legend is causing issues here. I don't know how you have implemented it, so difficult to predict the issue.

Maybe you can wait - while I work on custom-legend events by providing a public method to toggle series - so you don't have to manipulate series on your own.

**Comment by pnemi** [comment] 2018-10-11 04:55
It's not caused by my custom legend at all (I tested it just in case...).

**Comment by junedchhipa** [comment] 2018-10-11 05:03
Ah! ok.
I would appreciate if you take some time to create a codesandbox example as I still cannot reproduce it on my end.

**Comment by pnemi** [comment] 2018-10-25 13:56
Okay. I'm back. I got some time to isolate my graph environment and data from our project and I'm happy to say I've got it ready for you to explore its behaviour (as create-react-app project). Since this problem is serious and causes unpleasant user experience, I'd be very grateful if you fixed this.

Steps do reproduce my problem
**#1 way**
a) uncheck all series in legend
b) switch to week filter in tab bar
c) check second and/or fourth (or whatever series has data) => line will appear for a sec at first check, then disappear

**#2 way**
a) uncheck second and/or fourth (or whatever series has data) in legend
b) click on panning icon in toolbar
c) switch to week filter in tab bar
d) check second and/or fourth (or whatever series has data) => -||-

By the way, take a look at what becomes apexchart-series <path> after this – there's NaN all over the place (in 'd' attribute).

Thank you and have a good day.

[apex-error.zip](https://github.com/apexcharts/react-apexcharts/files/2515171/apex-error.zip)

**Comment by junedchhipa** [comment] 2018-10-25 18:53
Hey @pnemi 
I'll take a look at the zip file and will get back soon.

**Comment by junedchhipa** [comment] 2018-10-28 19:52
@pnemi Just to update you, I have started working on the bug and your demo is helpful in tracing the issue. Please wait until next week as this seems challenging at first glance 😁 
Thank you for the patience

**Comment by junedchhipa** [comment] 2018-10-31 14:57
This fix will be released in 2.1.9

**Closed** 2018-10-31 14:56 UTC
Labels: bug, work in progress

**Comment by pnemi** [comment] 2018-11-01 10:52
Nice! It works! (Although I noticed that now that unchecked series will become checked and visible on change, hopefully our customer won't mind so I don't have to deal with that)
Thank you so much again!

**Comment by junedchhipa** [comment] 2018-11-01 10:55
Yes, because a lot of things change internally when `updateOptions()` is called. So, currently, this was easiest for me to clean-up any previous data to avoid issues.
A small fix related to this I noticed after the push will be shipped in v2.2.0

You're welcome!
