### ISSUE TITLE
apex-charts throwing error in dev mode on react 18 

### ISSUE THREAD

**Issue by frindly** [apexcharts/react-apexcharts#475] opened 2023-01-12 21:19 UTC
The first time a page with a chart on it loads, only when in dev mode, the following error is thrown:

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'toString')

Call Stack
t.value
node_modules/apexcharts/dist/apexcharts.common.js (6:389691)
t.value
node_modules/apexcharts/dist/apexcharts.common.js (6:386053)
t.value
node_modules/apexcharts/dist/apexcharts.common.js (14:36706)
t.eval [as create]
node_modules/apexcharts/dist/apexcharts.common.js (6:4476)
eval
node_modules/apexcharts/dist/apexcharts.common.js (14:36097)
new Promise
<anonymous>
t.value
node_modules/apexcharts/dist/apexcharts.common.js (14:21667)
r.value
node_modules/react-apexcharts/dist/react-apexcharts.min.js (1:2694)
invokeLayoutEffectMountInDEV
node_modules/react-dom/cjs/react-dom.development.js (25133:0)
invokeEffectsInDev
node_modules/react-dom/cjs/react-dom.development.js (27351:0)
commitDoubleInvokeEffectsInDEV
node_modules/react-dom/cjs/react-dom.development.js (27327:0)
flushPassiveEffectsImpl
node_modules/react-dom/cjs/react-dom.development.js (27056:0)
flushPassiveEffects
node_modules/react-dom/cjs/react-dom.development.js (26984:0)
eval
node_modules/react-dom/cjs/react-dom.development.js (26769:0)
workLoop
node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
node_modules/scheduler/cjs/scheduler.development.js (239:0)
MessagePort.performWorkUntilDeadline
node_modules/scheduler/cjs/scheduler.development.js (533:0)

This happens with a very simple page with a chart.  If any other state changes happen on a page, the charts show up and behave as expected, its only on the first load that this crash occurs

```
import dynamic from 'next/dynamic';
const Chart = dynamic(() => import('react-apexcharts'), { ssr: false });

export default function ChartDemo() {
  return (
    <div>
      <Chart
        id="chart"
        type="bar"
        options={{}}
        series={[
          {
            name: '',
            data: [1, 2, 4, 5, 5],
          },
        ]}
        height={364}
      />
    </div>
  );
}
```

<img width="870" alt="Screen Shot 2023-01-12 at 1 18 42 PM" src="https://user-images.githubusercontent.com/1693926/212183395-25d35122-2807-42b1-bede-a9b066abdddb.png">

**Comment by lokimckay** [comment] 2023-01-14 08:21
@frindly take a look at [this comment](https://github.com/apexcharts/react-apexcharts/issues/467#issuecomment-1367061550)

**Comment by junedchhipa** [comment] 2024-07-14 11:00
Duplicate of #467

**Closed by junedchhipa** 2024-07-14 11:00 UTC
