### ISSUE TITLE
Wanting to make a certain UI with React-ApexChart

### ISSUE THREAD

**Issue by AyushShrivastava3110** [apexcharts/react-apexcharts#217] opened 2020-09-27 11:55 UTC
Facing issues creating a special case of Stacked Column and Row based chart like in the below picture.Please if someone can look into this.
![Screenshot (130)](https://user-images.githubusercontent.com/71870681/94364374-6a402980-00e6-11eb-9a93-f68e81c7bb2d.png)

**Comment by junedchhipa** [comment] 2020-10-06 12:44
Sorry, grouped + stacked column chart is not possible with ApexCharts yet.
Duplicate of #196

**Closed by junedchhipa** 2020-10-06 12:44 UTC
